In [2]:
import datetime
import gymnasium as gym
# import importlib
import numpy as np

from time import sleep

import backtothecode_gym
import backtothecode_gym.envs.lib.board as board_lib
import backtothecode_gym.envs.lib.renderer as renderer_lib
import backtothecode_players as players_lib

from backtothecode_gym.envs import BackToTheCodeEnvParams

def create_game(params):
    players = [
        players_lib.AIPlayer(
            id=params.HERO_ID,
            name='Hero',
        ),
        players_lib.RandomPlayer(
            id=params.OPPONENT_ID,
            name='Opponent',
            momentum=0.5
        )
    ]
    bttc = gym.make(
        id='BackToTheCode',
        players=players,
        renderer=renderer_lib.CanvasRenderer()
    )
    return bttc, players


def play_game(bttc, players, is_training=False, verbose=False):
    bttc.reset(is_training=is_training)
    terminated = False
    truncated = False
    while not terminated and not truncated:
        old_board = bttc.unwrapped.board.copy()
        action = hero.move(old_board, verbose=verbose)
        observation, reward, terminated, truncated, info = bttc.step(action)
        new_board = bttc.unwrapped.board.copy()
        if is_training:
            # Send feedback to the hero
            hero.feedback(old_board, action, reward, new_board, terminated or truncated)
        else:
            bttc.render()
            sleep(0.1)

In [ ]:
bttc, players = create_game(BackToTheCodeEnvParams)
hero, opponent = players

run_name = datetime.datetime.now().strftime('%Y%m%d-%H%M%S')     
print(run_name)
num_training_games = 30
for game_id in range(num_training_games):
    print(f"Game {game_id}... ", end='')
    play_game(bttc, players, is_training=True)
    for player in players:
        if player.trainable:
            player.train()
    print(f"Rounds: {bttc.round_number} Score: {hero.score}/{opponent.score}", hero.rewards)
    
hero.save(run_name)

print("Showtime!")
play_game(bttc, players, is_training=False)
    
bttc.close()

In [3]:
bttc, players = create_game(BackToTheCodeEnvParams)
hero, opponent = players
 
run_name = '20230827-112056'
hero.load(run_name)

print("Showtime!")
play_game(bttc, players, is_training=False, verbose=True)
    
bttc.close()

Showtime!
tensor([0.4532, 0.4617, 0.4030, 0.4602], grad_fn=<AddBackward0>)


/Users/tomwesolowski/miniconda3/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:335: UserWarning: WARN: No render fps was declared in the environment (env.metadata['render_fps'] is None or not defined), rendering may occur at inconsistent fps.
  logger.warn(


Canvas(height=696, sync_image_data=True, width=1050)

tensor([0.3091, 0.4045, 0.4409, 0.3567], grad_fn=<AddBackward0>)
tensor([0.4160, 0.4363, 0.4205, 0.3605], grad_fn=<AddBackward0>)
tensor([0.3091, 0.4045, 0.4409, 0.3567], grad_fn=<AddBackward0>)
tensor([0.4160, 0.4363, 0.4205, 0.3605], grad_fn=<AddBackward0>)
tensor([0.3091, 0.4045, 0.4409, 0.3567], grad_fn=<AddBackward0>)
tensor([0.4160, 0.4363, 0.4205, 0.3605], grad_fn=<AddBackward0>)
tensor([0.3091, 0.4045, 0.4409, 0.3567], grad_fn=<AddBackward0>)
tensor([0.4164, 0.4183, 0.1207, 0.3000], grad_fn=<AddBackward0>)
tensor([0.2498, 0.3307, 0.2374, 0.3387], grad_fn=<AddBackward0>)
tensor([0.2448, 0.3598, 0.2883, 0.3388], grad_fn=<AddBackward0>)
tensor([0.3091, 0.4045, 0.4409, 0.3567], grad_fn=<AddBackward0>)
tensor([0.2800, 0.3473, 0.1768, 0.2573], grad_fn=<AddBackward0>)
tensor([0.2498, 0.3307, 0.2374, 0.3387], grad_fn=<AddBackward0>)
tensor([0.2448, 0.3598, 0.2883, 0.3388], grad_fn=<AddBackward0>)


KeyboardInterrupt: 

In [3]:
# plot_scores = []
# plot_mean_scores = []
# total_score = 0
# record = 0
# agent = Agent()
# game = SnakeGameAI()
# while True:
#     # get old state
#     state_old = agent.get_state(game)

#     # get move
#     final_move = agent.get_action(state_old)

#     # perform move and get new state
#     reward, done, score = game.play_step(final_move)
#     state_new = agent.get_state(game)

#     # train short memory
#     agent.train_short_memory(state_old, final_move, reward, state_new, done)

#     # remember
#     agent.remember(state_old, final_move, reward, state_new, done)

#     if done:
#         # train long memory, plot result
#         game.reset()
#         agent.n_games += 1
#         agent.train_long_memory()

#         if score > record:
#             record = score
#             agent.model.save()

#         print('Game', agent.n_games, 'Score', score, 'Record:', record)

#         plot_scores.append(score)
#         total_score += score
#         mean_score = total_score / agent.n_games
#         plot_mean_scores.append(mean_score)
#             plot(plot_scores, plot_mean_scores)